# Site settings
title: alecive
email: alessandro.roncone@colorado.edu
url: https://alecive.github.io
phone: +1 (203) 606-3896
google-analytics-id: UA-80094809-1
description: "Personal website of Alessandro Roncone, also known as alecive, Ph.D. in robotics engineering, computer scientist, interaction designer, father and runner."
owner: Alessandro Roncone
owner-title: Ph.D.
owner-job: Robotics Engineer

# These should be put at the root of your website
resume-link: AlessandroRoncone_resume.pdf
cv-link: AlessandroRoncone_cv.pdf
cv-image: /img/cv.jpg

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github-alt
    url: http://github.com/alecive
  - title: linkedin
    url: https://www.linkedin.com/in/alessandroroncone
  - title: graduation-cap
    url: https://scholar.google.com/citations?user=nV-XGVIAAAAJ&hl
  # - title: calendar-o
  #   url: https://calendar.google.com/calendar/embed?&bgcolor=%23FFFFFF&src=alecive87%40gmail.com&color=%232952A3&src=l5g5teoouu34et18910uckvkhg%40group.calendar.google.com&color=%23711616&src=06ovc3en5h9bad60rmtu87ru8c%40group.calendar.google.com&color=%235229A3&ctz=America%2FNew_York

logo: /img/logo.svg

banner: "I am looking for students!"
banner-link: student_opportunities.html

# Postal address (add as many lines as necessary)
address:
  - line: 1111 Engineering Dr, ECES 124,
  - line: Computer Science Dept, University of Colorado,
  - line: Boulder, 80309, CO, U.S.A.

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  highlighter: rouge
  toc_levels: "1,2,3"
permalink: pretty
plugins:
  - jekyll-sitemap
  - rouge
  - jekyll-seo-tag
  - jemoji
  #- jekyll-mentions

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "_drafts"
    values:
      category: "blog"
      type: "article"
  -
    scope:
      path: "_posts"
    values:
      type: "article"
  -
    scope:
      path: "_posts/research"
    values:
      category: "research"
  -
    scope:
      path: "_posts/research/humanoid_robotics"
    values:
      subcategory: "Humanoid Robotics"
  -
    scope:
      path: "_posts/research/human_robot_collaboration"
    values:
      subcategory: "Human-Robot Collaboration"
  -
    scope:
      path: "_posts/design"
    values:
      category: "design"
  -
    scope:
      path: "_posts/blog"
    values:
      category: "blog"
  -
    scope:
      path: "_posts/hidden"
    values:
      category: "hidden"

# Some more default colors (hex-codes without the leading hash-tag),
# with a number of combinations to play with
color:
# ORIGINAL - B&W
  banner: 66a329                            # This is a green banner color (for red, use bf4040)
  articletext: 292929                       # This is the text color
  primary:  f9fafb                          # This is the background of the logo, light gray
  secondary: 3c3c3c                         # This is dark gray
  secondary-dark: 323232                    # This is darker gray
  secondary-alpha: rgba(40,40,40,.7)        # This is the same as the secondary color but with an alpha value
  # accent: 4982a7
  accent: 3d6c8b                            # This is a light blue accent
# ALTERNATIVE 0
  # articletext: 292929                     # This is the text color
  # primary: f9fafb                         # This is the gray color with a blue tint
  # secondary: 0892d0                       # This is the blue color
  # secondary-dark: 055c83                  # This is the blue color
  # secondary-alpha: rgba(84,99,116,.7)     # This is the same as the secondary color but with an alpha value
  # accent: e20e59                          # These are the pink accents
# ALTERNATIVE 1
  # primary: f9fafb                         # This is gray
  # secondary: ca6558                       # This is reddish
  # secondary-dark: b9493b                  # This is reddish
  # accent: 8ca08d                          # This is greenish
# ALTERNATIVE 2
  # secondary: 589ee4                       # This is blueish
  # secondary-dark: 368ade                  # This is blueish
  # accent: ed6152                          # This is reddish
# ALTERNATIVE 3
  # accent: 53c3cb                          # This is greenish
  # secondary: f4676d                       # This is reddish
  # secondary-dark: f24e55                  # This is reddish
